appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: m3zUvFO5Z64EBrSFQ/02j6cqfwUXF3cWJ1rA4VOShtTv9UOm5QT6H8v0LQRqudfeEiGDve28YjJEIefHpC6LtXN422bF35apwmteCXG7Y8iE+KxGJiWp2BuGt4DciabMOtb16u45Dp6/clVClPdRipanbrYA65EyxK8936ttnLmCDbZVVQrhOXpjwb2fxKFbW7f2Z2gyK23YeCL1N7z6uExY/Ja2Zbs4I9XpTPF6j57ps5wb4w5XfGC8kRwBOVfHDkRhD2mqLyZvg8LagJUomM0lRVakZ7yR8bc3b5nYjX19GiSPtDMtyJXv1d0uh/Ffco6WeFrj/dgi5M5EeGgSGAVP3fetrgZvMUkg1AzIid2HYdDmJxMPz3yiGdVQ3fvbn8K8YSSDpj2PZwlf+zSbXJ0qG/KhS2eoilq2BnNvO61K6c6c/Q1jkjscnR/rFlNxsW2Ij6uvLQBFeD/wTeI/Y4QE/k5hneV3EvL8i8fWfe9CkMZmY03LTrM+svqwY3uudPO79wsnjVi7NFIwgz3f37Pr/rGB1C+0dKSzwmOKtekzj6m07tjg9AMZrUJtLH9tHXHjoX0O9ZKk+wQWYDaJKHPVZ3PNI2/FYZkCwF6nYAeJFCfNB1V+WaVhZh8TL31v4cHsL7CpoC1J5plwgek5TgLEbGYcEPHq/hOwOmfbnCs=}
provider:
  win: azure
bot:
  automerge: true
